# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Exercise.create([
  { :title => "Scholar's mate", :description => "http://en.wikipedia.org /wiki/Scholar%27s_mate", :strmoves => "e2-e4, e7-e5, d1-Qh5, b8-Nc6, f1-Bc4, g8-Nf6, h5-Qxf7", :start => "a8-black-♜,b8-black-♞,c8-black-♝,d8-black-♛,e8-black-♚,f8-black-♝,g8-black-♞,h8-black-♜,a7-black-♟,b7-black-♟,c7-black-♟,d7-black-♟,e7-black-♟,f7-black-♟,g7-black-♟,h7-black-♟,a2-white-♟,b2-white-♟,c2-white-♟,d2-white-♟,e2-white-♟,f2-white-♟,g2-white-♟,h2-white-♟,a1-white-♜,b1-white-♞,c1-white-♝,d1-white-♛,e1-white-♚,f1-white-♝,g1-white-♞,h1-white-♜", :created_at => "2012-11-09 22:06:04", :updated_at => "2012-11-12 22:47:55" },
  { :title => "Fool's mate", :description => "http://en.wikipedia.org/wiki/Fool%27s_Mate", :strmoves => "f2-f3, e7-e5, g2-g4, d8-Qh4", :start => "a8-black-♜,b8-black-♞,c8-black-♝,d8-black-♛,e8-black-♚,f8-black-♝,g8-black-♞,h8-black-♜,a7-black-♟,b7-black-♟,c7-black-♟,d7-black-♟,e7-black-♟,f7-black-♟,g7-black-♟,h7-black-♟,a2-white-♟,b2-white-♟,c2-white-♟,d2-white-♟,e2-white-♟,f2-white-♟,g2-white-♟,h2-white-♟,a1-white-♜,b1-white-♞,c1-white-♝,d1-white-♛,e1-white-♚,f1-white-♝,g1-white-♞,h1-white-♜", :created_at => "2012-11-09 22:07:09", :updated_at => "2012-11-11 18:18:21" },
  { :title => "Pawn Movement", :description => "This is the description of how a pawn moves", :strmoves => "d4-d5, d5-d6, d6-e7", :start => "e7-black-♟,d4-white-♟", :created_at => "2012-11-09 22:08:06", :updated_at => "2012-11-09 22:08:06" }
], :without_protection => true )



Move.create([
  { :piece => "♟", :starting_coordinate => "e2", :ending_coordinate => "e4", :explaination => "Pawn goes e2 to e4", :created_at => "2012-11-12 01:33:04", :updated_at => "2012-11-12 21:14:56", :exercise_id => 1, :move_number => 1 },
  { :piece => "♟", :starting_coordinate => "e7", :ending_coordinate => "e5", :explaination => "Pawn goes from e7 to e5", :created_at => "2012-11-12 21:05:31", :updated_at => "2012-11-12 21:18:55", :exercise_id => 1, :move_number => 2 },
  { :piece => "♛", :starting_coordinate => "d1", :ending_coordinate => "h5", :explaination => "Queen goes from d1 to h5", :created_at => "2012-11-12 21:06:27", :updated_at => "2012-11-12 21:19:03", :exercise_id => 1, :move_number => 3 },
  { :piece => "♞", :starting_coordinate => "b8", :ending_coordinate => "c6", :explaination => "Knight goes b8 to c6", :created_at => "2012-11-12 21:07:10", :updated_at => "2012-11-12 21:19:09", :exercise_id => 1, :move_number => 4 },
  { :piece => "♝", :starting_coordinate => "f1", :ending_coordinate => "c4", :explaination => "Bishop goes f1 to c4", :created_at => "2012-11-12 21:07:35", :updated_at => "2012-11-12 21:19:18", :exercise_id => 1, :move_number => 5 },
  { :piece => "♞", :starting_coordinate => "g8", :ending_coordinate => "f6", :explaination => "Knight goes g8 to f6", :created_at => "2012-11-12 21:07:58", :updated_at => "2012-11-12 21:19:25", :exercise_id => 1, :move_number => 6 },
  { :piece => "♛", :starting_coordinate => "h5", :ending_coordinate => "f7", :explaination => "Queen goes h5 to f7 for checkmate", :created_at => "2012-11-12 21:08:31", :updated_at => "2012-11-12 21:19:32", :exercise_id => 1, :move_number => 7 }
], :without_protection => true )


