# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Exercise.create([
  { :title => "Scholar's mate", :description => "http://en.wikipedia.org/wiki/Scholar%27s_mate", :moves => "e2-e4, e7-e5, d1-Qh5, b8-Nc6, f1-Bc4, g8-Nf6, h5-Qxf7", :start => "a8-black-♜,b8-black-♞,c8-black-♝,d8-black-♛,e8-black-♚,f8-black-♝,g8-black-♞,h8-black-♜,a7-black-♟,b7-black-♟,c7-black-♟,d7-black-♟,e7-black-♟,f7-black-♟,g7-black-♟,h7-black-♟,a2-white-♟,b2-white-♟,c2-white-♟,d2-white-♟,e2-white-♟,f2-white-♟,g2-white-♟,h2-white-♟,a1-white-♜,b1-white-♞,c1-white-♝,d1-white-♛,e1-white-♚,f1-white-♝,g1-white-♞,h1-white-♜", :created_at => "2012-11-09 22:06:04", :updated_at => "2012-11-09 22:06:11" },
  { :title => "Fool's mate", :description => "http://en.wikipedia.org/wiki/Fool%27s_Mate", :moves => "f2-f3, e7-e5, g2-g4, d8-Qh4", :start => "a8-black-♜,b8-black-♞,c8-black-♝,d8-black-♛,e8-black-♚,f8-black-♝,g8-black-♞,h8-black-♜,a7-black-♟,b7-black-♟,c7-black-♟,d7-black-♟,e7-black-♟,f7-black-♟,g7-black-♟,h7-black-♟,a2-white-♟,b2-white-♟,c2-white-♟,d2-white-♟,e2-white-♟,f2-white-♟,g2-white-♟,h2-white-♟,a1-white-♜,b1-white-♞,c1-white-♝,d1-white-♛,e1-white-♚,f1-white-♝,g1-white-♞,h1-white-♜", :created_at => "2012-11-09 22:07:09", :updated_at => "2012-11-09 22:07:18" },
  { :title => "Pawn Movement", :description => "This is the description of how a pawn moves", :moves => "d4-d5, d5-d6, d6-e7", :start => "e7-black-♟,d4-white-♟", :created_at => "2012-11-09 22:08:06", :updated_at => "2012-11-09 22:08:06" }
], :without_protection => true )


